### ISSUE TITLE
Error with ProcessPageEditImageSelect on image field inside a repeater

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1055]
I have tested on two PW installs and keep getting this when I click to edit an image.

```
 TemplateFile: Unknown field images_repeater3297<pre>#0 /Users/ajones/Sites/pwtest/wire/core/Modules.php(441): ProcessPageEditImageSelect->init() #1 /Users/ajones/Sites/pwtest/wire/core/Modules.php(1012): Modules->initModule(Object(ProcessPageEditImageSelect), false) #2 /Users/ajones/Sites/pwtest/wire/core/Modules.php(919): Modules->getModule('ProcessPageEdit...') #3 /Users/ajones/Sites/pwtest/wire/core/ProcessController.php(135): Modules->get('ProcessPageEdit...') #4 /Users/ajones/Sites/pwtest/wire/core/ProcessController.php(209): ProcessController->getProcess() #5 [internal function]: ProcessController->___execute() #6 /Users/ajones/Sites/pwtest/wire/core/Wire.php(366): call_user_func_array(Array, Array) #7 /Users/ajones/Sites/pwtest/wire/core/Wire.php(321): Wire->runHooks('execute', Array) #8 /Users/ajones/Sites/pwtest/wire/core/admin.php(93): Wire->__call('execute', Array) #9 /Users/ajones/Sites/pwtest/wire/core/admin.php(93): ProcessController->execute() #10 /Users/ajones/Sites/pwtest/wire/modules/AdminTheme/AdminThemeDefault/controller.php(13): require('/Users/ajones/S...') #11 /Users/ajones/Sites/pwtest/site/templates/admin.php(15): require('/Users/ajones/S...') #12 /Users/ajones/Sites/pwtest/wire/core/TemplateFile.php(169): require('/Users/ajones/S...') #13 [internal function]: TemplateFile->___render() #14 /Users/ajones/Sites/pwtest/wire/core/Wire.php(366): call_user_func_array(Array, Array) #15 /Users/ajones/Sites/pwtest/wire/core/Wire.php(321): Wire->runHooks('render', Array) #16 /Users/ajones/Sites/pwtest/wire/modules/PageRender.module(356): Wire->__call('render', Array) #17 /Users/ajones/Sites/pwtest/wire/modules/PageRender.module(356): TemplateFile->render() #18 [internal function]: PageRender->___renderPage(Object(HookEvent)) #19 /Users/ajones/Sites/pwtest/wire/core/Wire.php(366): call_user_func_array(Array, Array) #20 /Users/ajones/Sites/pwtest/wire/core/Wire.php(321): Wire->runHooks('renderPage', Array) #21 /Users/ajones/Sites/pwtest/wire/core/Wire.php(388): Wire->__call('renderPage', Array) #22 /Users/ajones/Sites/pwtest/wire/core/Wire.php(388): PageRender->renderPage(Object(HookEvent)) #23 /Users/ajones/Sites/pwtest/wire/core/Wire.php(321): Wire->runHooks('render', Array) #24 /Users/ajones/Sites/pwtest/wire/modules/Process/ProcessPageView.module(172): Wire->__call('render', Array) #25 /Users/ajones/Sites/pwtest/wire/modules/Process/ProcessPageView.module(172): Page->render() #26 [internal function]: ProcessPageView->___execute(true) #27 /Users/ajones/Sites/pwtest/wire/core/Wire.php(366): call_user_func_array(Array, Array) #28 /Users/ajones/Sites/pwtest/wire/core/Wire.php(321): Wire->runHooks('execute', Array) #29 /Users/ajones/Sites/pwtest/index.php(208): Wire->__call('execute', Array) #30 /Users/ajones/Sites/pwtest/index.php(208): ProcessPageView->execute(true) #31 {main}</pre>
```

**Comment by adrianbj** [comment]
I don't use repeaters so this doesn't actually affect me, but I am not sure how this is a fix - it seems like clicking the edit option still opens the edit dialog (as opposed to the preview lightbox), but there are no editing options available. It looks like you got rid of the crop icon when hovering on the image, but you can still click the filename, which results in the non-functional edit modal opening up.

**Comment by ryancramerdesign** [comment]
It's just an enlargement of the image in a modal. The link still needs to
be there even if it's just to the image. ProcessPageEditImageSelect is not
involved in the contents of it at all. The error was that an exception was
getting thrown, so that's what is being fixed here.

**Comment by adrianbj** [comment]
Ok, I guess it's just confusing the to see the little pencil icon (indicating the ability to edit the image), but then not have any editing tools. Are you planning on adding image edit support for repeaters at some point?

Fair enough that the issue / error has been fixed though :)

**Comment by ryancramerdesign** [comment]
Image edit support for repeaters actually isn't a problem. It's the "what
happens after" part that is... the updating of the parent window becomes a
lot more tricky, and a little more than I want to get into at the moment.
But I think I would like to add edit support for these images a little
later. For the moment I want to limit how much of this stuff I get into so
that 2.6 can come out sooner, so mostly focused on fixing bugs.
