### ISSUE TITLE
Fatal Error after adding Imagefield to user template

### ISSUE THREAD

**Issue by kixe** [ryancramerdesign/ProcessWire#1259]
Error: Exception: New page '/admin/access/users//' must be saved before files can be accessed from it (in [...]/wire/core/PagefilesManager.php line 262)
#0 [...]/dev/wire/core/PagefilesManager.php(253): PagefilesManager->___path()
#1 [...]/dev/wire/core/PagefilesManager.php(213): PagefilesManager->path()
#2 [...]/dev/wire/core/PagefilesManager.php(67): PagefilesManager->createPath()
#3 [...]/dev/wire/core/PagefilesManager.php(55): PagefilesManager->init(Object(Page))
#4 [...]/dev/wire/core/Page.php(1921): PagefilesManager->__construct(Object(Page))
#5 [...]/dev/wire/core/Pagefiles.php(74): Page->filesManager()
#6 [...]/wire/core/Pagefiles.php(58): Pagefiles->setPage(Object(Page))
#7 [...]/dev/wire/modules/Fieldtype/FieldtypeImage.module(33): Pagefiles->__construct(Object(Page))
#8 [...]/dev/wire/core/Fieldtype.php(479): FieldtypeImage->getBlankValue(Object(Pag

**Comment by ryancramerdesign** [comment]
What is the API code that causes the error to trigger? PW doesn't allow any access to a file or image field on a Page before it has an id, because the directories where files are stored is named the same as the id. For this reason, a page must be saved before attempting to access file fields from it.

**Comment by kixe** [comment]
I am using a module which is based on your FormTemplateProcessor (many changings). I use it to provide frontend forms, to edit existing pages, creating new pages, sending emails. To provide the Form based on Templates a page is instantiated but not saved. FieldtypeFile or Image is part of one of those templates. I want to provide the Inputfield, NOT access a file. PageFilesManager doesn't allow this.
I found a workaround to prevent this error. In case of a unsaved page instance (id = 0) a hook is called from the render() method:
$this->addHookBefore('PagefilesManager::path', function ($e) {$e->replace = true;$e->return = null;});
