### ISSUE TITLE
~= operator not working after update from 302 to 303

### ISSUE THREAD

**Issue by TomS-** [ryancramerdesign/ProcessWire#1590]
Hi Ryan,

Thank you for your changes to ~=, this will help massively with a project I'm currently working on. However after updating from 302 to 303, using that selector gives me the following error.

```
Error: Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'DatabaseQuerySelect' in 'order clause' (in /var/sites/a/asg.returnonideas.co.uk/public_html/wire/core/PageFinder.php line 305)

#0 [internal function]: ProcessWire\PageFinder->___find(Object(ProcessWire\Selectors), Array)
#1 /var/sites/a/asg.returnonideas.co.uk/public_html/wire/core/Wire.php(264): call_user_func_array(Array, Array)
#2 /var/sites/a/asg.returnonideas.co.uk/public_html/wire/core/WireHooks.php(550): ProcessWire\Wire->_callMethod('___find', Array)
#3 /var/sites/a/asg.returnonideas.co.uk/public_html/wire/core/Wire.php(288): ProcessWire\WireHooks->runHooks(Object(ProcessWire\PageFinder), 'find', Array)
#4 /var/sites/a/asg.returnonideas.co.uk/public_html/wire/core/Pages.php(229): ProcessWire\Wire->__call('find', Array)
#5 /var/sites/a/asg.returnonideas.co.uk/public_html/wire/core/Pages.php(229): ProcessWire\PageFinder->find(Object(ProcessWire\Selectors), Array)
#6 [internal function]: ProcessWire\Pages->___find('template=docume...')
#

This error message was shown because: you are logged in as a Superuser. Error has been logged.
```

https://processwire.com/talk/topic/11754-search-not-working-as-intended/

**Comment by ryancramerdesign** [comment]
Thanks @TomS- I have pushed a fix for this issue to devns.

**Comment by isellsoap** [comment]
@TomS- Can you close this issue please? Thank you!
