### ISSUE TITLE
3.0.3 devns errors removing language from site-languages profile

### ISSUE THREAD

**Issue by CanRau** [ryancramerdesign/ProcessWire#1593]
Hola, just got a huge error flood (more or less..)

Got a fresh install of PW 3.0.3. running, used the multi language profile as starting point.
But because I currently only need 2 languages I deleted Finnish and (by clicking the delete button on the delete tab of the language editing dialog)

__from /logs/errors.txt, therefore showed up as usual notifications__
```
2016-01-01 18:15:14	can	http://www.proceswire.dev/engineer/setup/languages/edit/?id=1013	SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'name1013_parent_id'; check that column/key exists (LanguageSupportPageNames)
2016-01-01 18:15:14	can	http://www.proceswire.dev/engineer/setup/languages/edit/?id=1013	SQLSTATE[42S22]: Column not found: 1054 Unknown column 'field_title.data1013' in 'field list' [pageClass=Language, template=language] (WireLog)
2016-01-01 18:15:14	can	http://www.proceswire.dev/engineer/setup/languages/edit/?id=1013	SQLSTATE[42S22]: Column not found: 1054 Unknown column 'field_title.data1013' in 'field list' [pageClass=Language, template=language] (WireLog)
2016-01-01 18:15:15	can	http://www.proceswire.dev/engineer/setup/languages/edit/?id=1013	SQLSTATE[42S22]: Column not found: 1054 Unknown column 'field_title.data1013' in 'field list' [pageClass=Role, template=role] (WireLog)
2016-01-01 18:15:15	can	http://www.proceswire.dev/engineer/setup/languages/	Error: 	Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'field_title.data1013' in 'field list' (in ../htdocs/processwire/happyfamily/wire/core/Pages.php line 2154)  #0 ../htdocs/processwire/happyfamily/wire/core/Pages.php(2154): PDOStatement->execute() #1 ../htdocs/processwire/happyfamily/wire/core/Pages.php(576): ProcessWire\Pages->executeQuery(Object(PDOStatement)) #2 ../htdocs/processwire/happyfamily/wire/core/Pages.php(279): ProcessWire\Pages->getById(Array, Array) #3 [internal function]: ProcessWire\Pages->___find('id>0, sort=name...', Array) #4 ../htdocs/processwire/happyfamily/wire/core/Wire.php(264): call_user_func_array(Array, Array) #5 ../htdocs/processwire/happyfamily/wire/core/WireHooks.php(550): ProcessWire\Wire->_callMethod('___find', Array) #6 ../htdocs/processwire/happyfamily/wire/core/Wire.php(288): ProcessWire\WireHooks->runHooks(Object(ProcessWire\Pages), 'find', Array) #7 /Users/admi
```
The errors.txt ends like this so I didn't forget to copy the rest..

__The following were plain errors above admin output__
```
Notice: Undefined property: ProcessWire\User::$language in /Users/admin/Can/htdocs/processwire/happyfamily/wire/modules/LanguageSupport/LanguageSupportFields.module on line 286
Notice: Undefined property: ProcessWire\User::$language in /Users/admin/Can/htdocs/processwire/happyfamily/wire/core/PageFinder.php on line 1040
Notice: Undefined property: ProcessWire\User::$language in /Users/admin/Can/htdocs/processwire/happyfamily/wire/modules/LanguageSupport/LanguageSupportFields.module on line 286
Notice: Undefined property: ProcessWire\User::$language in /Users/admin/Can/htdocs/processwire/happyfamily/wire/core/PageFinder.php on line 1040
Notice: Undefined property: ProcessWire\User::$language in /Users/admin/Can/htdocs/processwire/happyfamily/wire/modules/LanguageSupport/LanguageSupportFields.module on line 286
Notice: Undefined property: ProcessWire\User::$language in /Users/admin/Can/htdocs/processwire/happyfamily/wire/core/PageFinder.php on line 1040
```

To me the database looks good, no instance of any data1013 or name1013, so it seems like pw already cleaned up and then, maybe tried again and threw the errors?

__AHA__ maybe the redirection didn't worked properly, because it stayed on the edit page of the finnish language which i just deleted and therefore the errors make kinda sense, when trying to edit something not existing anymore..

**Comment by ryancramerdesign** [comment]
Thanks Can, I've pushed a fix for this issue in the latest commit.

**Comment by CanRau** [comment]
Kay this is the only error left
```
SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'name1013_parent_id'; check that column/key exists
```
Though this time it redirected back to /setup/languages/, the message showed up in user notifications and the database seems to be fine :)

Could only be a little confusing..
