### ISSUE TITLE
Uninstalled LanguageSupportPageNames error

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1789]
In latest dev. I have tried to set the LanguageSupportPageNames to not autoload while testing something. It didn't work and the name fields still showed, so I tried to uninstall the module and got this error when clicking submit. I can't find out why and how to fix it. Now this error shows always.

 Error: Exception: Unknown language (in /Applications/MAMP/htdocs/sandbox/wire/modules/LanguageSupport/Languages.php line 205)

#0 /Applications/MAMP/htdocs/sandbox/wire/core/PagesLoader.php(667): ProcessWire\Languages->setLanguage(NULL)
#1 /Applications/MAMP/htdocs/sandbox/wire/core/Pages.php(422): ProcessWire\PagesLoader->getPath(2, Array)
#2 /Applications/MAMP/htdocs/sandbox/wire/core/ProcessWire.php(322): ProcessWire\Pages->getPath(2)
#3 /Applications/MAMP/htdocs/sandbox/wire/core/ProcessWire.php(118): ProcessWire\ProcessWire->load(Object(ProcessWire\Config))
#4 /Applications/MAMP/htdocs/sandbox/index.php(52): ProcessWire\ProcessWire->__construct(Object(ProcessWire\Config))
#5 {main}

**Comment by somatonic** [comment]
I found that the flags of LanguageSupport and LanguageSupportPageNames had a flag of 19, after changing to 3 it started working again.

**Comment by ryancramerdesign** [comment]
Glad you found a fix. That advanced mode option to disable autoload modules can be dangerous in some cases like this. I figured keeping it in advanced mode was warranted, but maybe the option should be removed entirely. I haven't actually needed to use it before, but had added it at someone's request.
