### ISSUE TITLE
404 on /site/laskdjasdj

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#399]
http://site.com/site/sdfds

I get this on a multilanguage site. Of course the language methods do not work.

```
Error: Exception: Method Page::localUrl does not exist or is not callable in this context (in /home/www-data/processwire/wire/core/Wire.php line 320)

#0 /home/www-data/xxx/site/templates/views/inc/header.inc(55): Wire->__call('localUrl', Array)
#1 /home/www-data/xxx/site/templates/views/inc/header.inc(55): Page->localUrl(Object(Language))
#2 /home/www-data/xxx/site/templates/views/_output.php(92): include('/home/www-data/...')
#3 /home/www-data/xxx/site/templates/basic-page.php(184): include('/home/www-data/...')
#4 /home/www-data/processwire/wire/core/TemplateFile.php(140): require('/home/www-data/...')
#5 [internal function]: TemplateFile->___render()
#6 /home/www-data/processwire/wire/core/Wire.php(359): call_user_func_array(Array, Array)
#7 /home/www-data/processwire/wire/core/Wire.php(317): Wire->runHooks('render', Array)
#8 /home/www-data/processwire/wire/modules/PageRender.module(337): Wire->__call('render', Array)
#9 /home/www-data/processwire/wire/modules/PageRender.
```

whereas

http://site.com/kjlasd/asd doesn't give an error

**Comment by somatonic** [comment]
On a install where language support is installed, when I browse to url /site/asklaejasjelashe I get redirected to home! That's not good from a SEO perspective too.
