### ISSUE TITLE
Fatal Error on admin login without enough permission

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#765]
If someone tries to login to the admin backend without enough permission I get this fatal error:

Fatal error: Exception: Unknown Selector operator: '' -- was your selector value properly escaped? field='invitation', value='-codes', selector: 'name=page-edit, invitation-codes, sort=sort, parent_id=31, template=permission' (in …wire/core/Selectors.php line 247) #0 …wire/core/Selectors.php(284): Selectors->create('invitation', '', '-codes') #1 …wire/core/Selectors.php(81): Selectors->extractString('name=page-edit,...') #2 …wire/core/Pages.php(165): Selectors->__construct('name=page-edit,...') #3 [internal function]: Pages->___find('name=page-edit,...', Array) #4 …wire/core/Wire.php(389): call_user_func_array(Array, Array) #5 …wire/core/Wire.php(344): Wire->runHooks('find', Array) #6 …wire/ in …index.php on line 226

ProcessWire Version is 2.5.3 stable

**Comment by LostKobrakai** [comment]
Just to answer this before closing. The dash is the issue. Only underscores are allowed for fields.
