### ISSUE TITLE
Random "TemplateFile: No download URL specified" when updating module

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#946]
I get this occasionally when updating a module. Usually re-running the update works just fine, so I have no idea how to reproduce at the moment.

```
TemplateFile: No download URL specified<pre>#0 [internal function]: ProcessModule->___executeDownload() #1 /path/wire/core/Wire.php(365): call_user_func_array(Array, Array) #2 /path/wire/core/Wire.php(320): Wire->runHooks('executeDownload', Array) #3 /path/wire/core/ProcessController.php(213): Wire->__call('executeDownload', Array) #4 /path/wire/core/ProcessController.php(213): ProcessModule->executeDownload() #5 [internal function]: ProcessController->___execute() #6 /path/wire/core/Wire.php(365): call_user_func_array(Array, Array) #7 /path/wire/core/Wire.php(320): Wire->runHooks('execute', Array) #8 /path/wire/core/admin.php(85): Wire->__call('execute', Array) #9 /path/wire/core/admin.php(85): ProcessController->execute() #10 /path/wire/modules/AdminTheme/AdminThemeDefault/controller.php(13): require('/path/...') #11 /path/site/templates/admin.php(15): require('/path/...') #12 /path/wire/core/TemplateFile.php(169): require('/path/...') #13 [internal function]: TemplateFile->___render() #14 /path/wire/core/Wire.php(365): call_user_func_array(Array, Array) #15 /path/wire/core/Wire.php(320): Wire->runHooks('render', Array) #16 /path/wire/modules/PageRender.module(356): Wire->__call('render', Array) #17 /path/wire/modules/PageRender.module(356): TemplateFile->render() #18 [internal function]: PageRender->___renderPage(Object(HookEvent)) #19 /path/wire/core/Wire.php(365): call_user_func_array(Array, Array) #20 /path/wire/core/Wire.php(320): Wire->runHooks('renderPage', Array) #21 /path/wire/core/Wire.php(387): Wire->__call('renderPage', Array) #22 /path/wire/core/Wire.php(387): PageRender->renderPage(Object(HookEvent)) #23 /path/wire/core/Wire.php(320): Wire->runHooks('render', Array) #24 /path/wire/modules/Process/ProcessPageView.module(172): Wire->__call('render', Array) #25 /path/wire/modules/Process/ProcessPageView.module(172): Page->render() #26 [internal function]: ProcessPageView->___execute(true) #27 /path/wire/core/Wire.php(365): call_user_func_array(Array, Array) #28 /path/wire/core/Wire.php(320): Wire->runHooks('execute', Array) #29 /path/index.php(231): Wire->__call('execute', Array) #30 /path/index.php(231): ProcessPageView->execute(true) #31 {main}</pre>
```

**Comment by ryancramerdesign** [comment]
I've not seen this one yet. I'll keep an eye out for it. Lets leave this here in case anyone else sees it and can add more about how to reproduce.

**Comment by apeisa** [comment]
I also got this once, when updating the core through UI. Tried again and it
worked.
